# Generated by Django 2.2 on 2020-04-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_photo',
            field=models.ImageField(upload_to='apps/products/templates/product_images'),
        ),
    ]
