# Generated by Django 2.2 on 2020-04-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200413_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_photo',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
