# Generated by Django 2.2 on 2020-04-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200414_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
