# Generated by Django 3.0.5 on 2020-04-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbilling',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customershipping',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
