# Generated by Django 2.2 on 2020-04-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user_level',
        ),
    ]
